apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: workshop-dev
spec:
  selector:
    matchLabels:
      app: api
  replicas: 2
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
        - name: secret-docker
      containers:
      - name: pun-api
        image: ghcr.io/kkgo-software-engineering/workshop:21d9805d772d54f180298a54653e02109804be6a
        imagePullPolicy: Always
        ports:
        - containerPort: 1323
        envFrom:
          - configMapRef:
              name: app-env-config
          - secretRef:
              name: secret-config
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /healthz
            port: 1323
            httpHeaders:
            - name: Authorization
              value: 'basic YWRtaW46c2VjcmV0'
          initialDelaySeconds: 3
          periodSeconds: 3
