name: Dev environment CI and CD

on:
  push:
    branches: [main, hotfix]

jobs:
  # ==============
  # CI task
  # ==============
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: Setup SHA
        run: echo "GITHUB_SHA=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Unit test
        run: make test-unit

      - name: Integration test inside Docker-compose
        run: make test-integration
      
      - name: E2E test inside Docker-compose
        run: make test-e2e

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/<your-github-account>/workshop:${{ env.GITHUB_SHA }}

      - name: Login ghcr.io
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.WORKFLOW_TOKEN }}
          logout: true
      
      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          tags: |
            ghcr.io/<your-github-account>/workshop:${{ env.GITHUB_SHA }}
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  # ==============
  # CD DEV task
  # ==============
  gitops-dev-versioning:
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: config git
        run: |
          git --version
          git config user.name "robot"
          git config user.email "root@aorjoa.link"
        
      - name: change image tag to deploy dev
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          sed -i -E "s/ghcr.io\/<your-github-account>\/workshop.*$/ghcr.io\/<your-github-account>\/workshop:${GITHUB_SHA}/" infra/gitops/dev/deployment.yml
          git add infra/gitops/dev/deployment.yml
          git commit -m "[skip actions] ðŸ¤– change dev docker image version to ${GITHUB_SHA}"
          git pull --rebase
          git push

      - name: change image tag to deploy hotfix
        if: ${{ github.ref == 'refs/heads/hotfix' }}
        run: |
          sed -i -E "s/ghcr.io\/<your-github-account>\/workshop.*$/ghcr.io\/<your-github-account>\/workshop:${GITHUB_SHA}/" infra/gitops/hotfix/deployment.yml
          git add infra/gitops/hotfix/deployment.yml
          git commit -m "[skip actions] ðŸ¤– change hotfix docker image version to ${GITHUB_SHA}"
          git pull --rebase
          git push

      - name: set default docker image tag fot prd
        run: |
          sed -i -E "s/default: .*/default: ${GITHUB_SHA}/" .github/workflows/prd-cd.yaml
          git add .github/workflows/prd-cd.yaml
          git commit -m "[skip actions] ðŸ¤– change default docker tag"
          git pull --rebase
          git push
