name: Prd environment CD

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'ğŸ”¦ QA lead already approved'
        required: true
        type: boolean
      sign-off:
        description: 'ğŸ“ Make sure PO sign-off'
        required: true
        type: boolean
      deploy-tag:
        description: 'ğŸ¯ Deploy docker tag'
        required: true
        type: string
        default: f67923143885f3ba3f00a91fceda103d6e9b1103

jobs:
  # ==============
  # CD Prd task
  # ==============
  gitops-prd-versioning:
    runs-on: ubuntu-latest 
    steps:
      - name: verify manual input
        run: |
          { if [ '${{ inputs.test }}' = 'false' ]; then echo "ğŸ”¦ QA lead not approve yet"; exit 1; fi }
          { if [ '${{ inputs.sign-off }}' = 'false' ]; then echo "ğŸ“ Need PO sign-off"; exit 1; fi }
        
      - name: checkout
        uses: actions/checkout@v2

      - name: config git
        run: |
          git --version
          git config user.name "robot"
          git config user.email "root@aorjoa.link"
        
      - name: change image tag
        run: |
          sed -i -E "s/ghcr.io\/kkgo-software-engineering\/workshop.*$/ghcr.io\/kkgo-software-engineering\/workshop:${{ inputs.deploy-tag }}/" infra/gitops/prd/deployment.yml
          git add infra/gitops/prd/deployment.yml
          git commit -m "[skip actions] ğŸ¤– change prd docker image version to ${{ inputs.deploy-tag }}"
          git pull --rebase
          git push