name: Prd environment CD

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'ğŸ”¦ QA lead already approved'
        required: true
        type: boolean
      sign-off:
        description: 'ğŸ“ Make sure PO sign-off'
        required: true
        type: boolean
      deploy-tag:
        description: 'ğŸ¯ Deploy docker tag : '
        required: true
        type: string

jobs:
  # ==============
  # CD Prd task
  # ==============
  gitops-prd-versioning:
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image
    steps:
      - name: varify manual input
        run: |
          [[ "${{ inputs.test }}" ]] || { echo "ğŸ”¦ QA lead not approve yet" ; exit 1; }
          [[ "${{ inputs.sign-off }}" ]] || { echo "ğŸ“ Need PO sign-off" ; exit 1; }
        
      - name: checkout
        uses: actions/checkout@v2
        
      - name: change image tag
        run: |
          git --version
          git config user.name "robot"
          git config user.email "root@aorjoa.link"
          sed -i -E "s/ghcr.io\/kkgo-software-engineering\/workshop.*$/ghcr.io\/kkgo-software-engineering\/workshop:${{ inputs.deploy-tag }}/" infra/gitops/prd/deployment.yml
          git add infra/gitops/dev/deployment.yml
          git commit -m "[skip actions] ğŸ¤– change prd docker image version to ${{ inputs.deploy-tag }}"
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: kkgo-software-engineering/workshop
          branch: main